name: data1030
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - statsmodels
  - shap
  - jupyterlab
  - openpyxl
  - mysql-connector-python
  - fsspec
  - patsy
  - pip
  - pip:
      - ucimlrepo==0.0.7
